apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackfusion-deployment
spec:
  selector:
    matchLabels:
      app: stackfusion
  replicas: 1
  template:
    metadata:
      labels:
        app: stackfusion
    spec:
      containers:
      - name: stackfusion-container
        image: balcha/stackfusion
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stackfusion-service
spec:
  selector:
    app: stackfusion
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
